xo:
  # build: .
  image: interlegis/xen-orchestra:5.1.3-6
  ports:
    - "8080:80"
  links:
    - redis:redis
redis:
  image: bitnami/redis:latest
  environment:
    - REDIS_REPLICATION_MODE=master
    - REDIS_PASSWORD=aGoodRedisPassword
  
